version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my_network
    volumes:
      - ./files:/app/files  # Mapeamento da pasta 'files' no host para o contêiner
  db:
    image: postgres
    environment:
      POSTGRES_DB: persistencia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - my_network
networks:
  my_network:
